In [1]:
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Image
from qutip import *

### Quantum Objects

In [18]:
q = Qobj([[1], [0]])
q

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [19]:
# get dimension
q.dims

[[2], [1]]

In [20]:
# data type
q.data

<2x1 sparse matrix of type '<class 'numpy.complex128'>'
	with 1 stored elements in Compressed Sparse Row format>

In [21]:
# dense matrix representation
q.full()

array([[1.+0.j],
       [0.+0.j]])

In [22]:
# list additional properties
q.isherm, q.type

(False, 'ket')

### Quantum Objects in Calculations

In [26]:
sy = Qobj([[0,-1j], [1j,0]]) # sigma_y Pauli operator
sy

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [27]:
sz = Qobj([[1,0], [0,-1]])
sz

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [39]:
# Example hamiltonian
H = 1.0 * sz + 0.1 * sy

print('Qubit Hamiltonian = \n')
H

Qubit Hamiltonian = 



Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.+0.j   0.-0.1j]
 [ 0.+0.1j -1.+0.j ]]

In [41]:
# Example of hermitian conjugate using nonhermitian matrix
m = Qobj([[0,2j], [1,1]])
m

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+0.j 0.+2.j]
 [1.+0.j 1.+0.j]]

In [42]:
# hermitian conjugate
m.dag()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+0.j 1.+0.j]
 [0.-2.j 1.+0.j]]

In [43]:
# Trace
m.tr()

1.0

In [45]:
# Eigen energies of the Hamiltonian
H.eigenenergies()

array([-1.00498756,  1.00498756])

In [48]:
#help(Qobj)
#dir(Qobj)

### States and Operators

In [49]:
# fundamental basis states (fock states of oscillator modes)

N = 2 # number of states in the Hilbert space
n = 1 # the state that will be occupied

basis(N,n)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [50]:
fock(4, 2)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

In [51]:
# a coherent state
coherent(N=10, alpha=1.0)

Quantum object: dims = [[10], [1]], shape = (10, 1), type = ket
Qobj data =
[[0.60653066]
 [0.60653066]
 [0.42888194]
 [0.24761511]
 [0.12380753]
 [0.0553686 ]
 [0.02260303]
 [0.00854887]
 [0.00299672]
 [0.00110007]]